/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlanificacionDeDisco;

import javax.swing.JOptionPane;

/**
 *
 * @author irmal
 */
public class Ejercicios extends javax.swing.JFrame {
boolean correcto=true;
    /**
     * Creates new form Ejercicios
     */
    public Ejercicios() {
        initComponents();
        this.setLocationRelativeTo(null);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simuladorPanel = new javax.swing.JPanel();
        platosLabel = new javax.swing.JLabel();
        numeroDePlatosTxt = new javax.swing.JTextField();
        cilindrosLabel = new javax.swing.JLabel();
        numeroDeCilindrosTxt = new javax.swing.JTextField();
        numeroDeSectoresxPistaTxt = new javax.swing.JTextField();
        sectoresLabel = new javax.swing.JLabel();
        busquedaLabel = new javax.swing.JLabel();
        velocidadLabel = new javax.swing.JLabel();
        velocidadDeGiro = new javax.swing.JTextField();
        tiempoDeBusquedaTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        peticion1Label = new javax.swing.JLabel();
        peticion1Txt = new javax.swing.JTextField();
        peticion2Label = new javax.swing.JLabel();
        peticion2Txt = new javax.swing.JTextField();
        iniciarEjerciciosBtn = new javax.swing.JButton();
        menuBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador de Discos Duros");
        setResizable(false);

        platosLabel.setText("Número de platos");

        numeroDePlatosTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroDePlatosTxtActionPerformed(evt);
            }
        });

        cilindrosLabel.setText("Número de cilindros");

        sectoresLabel.setText("Número de sectores/pista ");

        busquedaLabel.setText("Tiempo de búsqueda (ms)");

        velocidadLabel.setText("Velocidad de giro (s)");

        peticion1Label.setText("Petición 1");

        peticion2Label.setText("Petición 2");

        javax.swing.GroupLayout simuladorPanelLayout = new javax.swing.GroupLayout(simuladorPanel);
        simuladorPanel.setLayout(simuladorPanelLayout);
        simuladorPanelLayout.setHorizontalGroup(
            simuladorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simuladorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(simuladorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cilindrosLabel)
                    .addComponent(velocidadLabel)
                    .addComponent(peticion1Label)
                    .addGroup(simuladorPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(busquedaLabel))
                    .addComponent(platosLabel)
                    .addComponent(sectoresLabel)
                    .addComponent(peticion2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(simuladorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(simuladorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(peticion1Txt)
                        .addComponent(tiempoDeBusquedaTxt)
                        .addComponent(velocidadDeGiro)
                        .addComponent(numeroDeCilindrosTxt)
                        .addComponent(numeroDeSectoresxPistaTxt)
                        .addComponent(numeroDePlatosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(peticion2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
        simuladorPanelLayout.setVerticalGroup(
            simuladorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simuladorPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(simuladorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(simuladorPanelLayout.createSequentialGroup()
                        .addGroup(simuladorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numeroDePlatosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(platosLabel))
                        .addGap(18, 18, 18)
                        .addGroup(simuladorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numeroDeCilindrosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cilindrosLabel))
                        .addGap(18, 18, 18)
                        .addGroup(simuladorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numeroDeSectoresxPistaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sectoresLabel))
                        .addGap(18, 18, 18)
                        .addGroup(simuladorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tiempoDeBusquedaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(busquedaLabel))
                        .addGap(18, 18, 18)
                        .addGroup(simuladorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(velocidadDeGiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(velocidadLabel)))
                    .addGroup(simuladorPanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(simuladorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peticion1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peticion1Label))
                .addGap(18, 18, 18)
                .addGroup(simuladorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peticion2Label)
                    .addComponent(peticion2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        iniciarEjerciciosBtn.setText("Iniciar");
        iniciarEjerciciosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarEjerciciosBtnActionPerformed(evt);
            }
        });

        menuBtn.setText("Menu");
        menuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(simuladorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(iniciarEjerciciosBtn)
                        .addGap(18, 18, 18)
                        .addComponent(menuBtn)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(simuladorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuBtn)
                    .addComponent(iniciarEjerciciosBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarEjerciciosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarEjerciciosBtnActionPerformed
        setCorrecto();
    
        if(correcto==true ){
            //desactivar form actual y mostrar el siguiente
            this.setVisible(false);
        ResultadosEjercicios r= new ResultadosEjercicios(); r.setVisible(correcto);
        int platos,numeroDePistasxSuperficie,numeroDeSectoresxPista;
        int tiempoDeBusqueda,rps,pedido1,pedido2;
        platos=Integer.parseInt(numeroDePlatosTxt.getText());
        numeroDePistasxSuperficie=Integer.parseInt(numeroDeCilindrosTxt.getText());
        numeroDeSectoresxPista=Integer.parseInt(numeroDeSectoresxPistaTxt.getText());
        tiempoDeBusqueda=Integer.parseInt(tiempoDeBusquedaTxt.getText());
        rps=Integer.parseInt(velocidadDeGiro.getText());
        pedido1=Integer.parseInt(peticion1Txt.getText());
        pedido2=Integer.parseInt(peticion2Txt.getText());
        int TR, sectoresxcilindro;
        
        EjerciciosDeDiscos disco=  new  EjerciciosDeDiscos(platos,numeroDePistasxSuperficie,numeroDeSectoresxPista,tiempoDeBusqueda,rps,pedido1,pedido2);
        TR=disco.calcularTiempoRotacional();
        r.settiempoRotacionalLabel(TR); 
        //calcularSectoresxCilindro(int numeroCabezas, int numeroDeSectoresxPista )
        sectoresxcilindro=disco.calcularSectoresxCilindro(disco.getNumeroDeCabezas(),numeroDeSectoresxPista);
        r.setsectoresXCilindrosLabel(sectoresxcilindro);
        
        disco.agregarCabeza(disco.calcularCabeza(pedido1, sectoresxcilindro));
        disco.agregarCabeza(disco.calcularCabeza(pedido2, sectoresxcilindro));
        
        int c1=disco.calcularCilindro(pedido1, sectoresxcilindro), c2=disco.calcularCilindro(pedido2, sectoresxcilindro);
        disco.agregarCilindro(c1);
        disco.agregarCilindro(c2);
        if(pedido1>pedido2){disco.agregarSector(disco.calcularSector(pedido1, sectoresxcilindro)+1);}
        else{disco.agregarSector(disco.calcularSector(pedido1, sectoresxcilindro));}
        
        disco.agregarSector(disco.calcularSector(pedido2, sectoresxcilindro));
        
        //EjerciciosDeDiscos(int numeroDePlatos, int numeroDePistasxSuperficie, int numeroDeSectoresxPista, int tiempoDeBusqueda, int velocidadDeGiro, int pedido1, int pedido2) {
       int cilindrosRecorridos= disco.calcularCilindrosRecorridos(c1, c2);
       int tiempoPedidos= disco.calcularTiempoRecorridoPedidos(cilindrosRecorridos);
       int cantSectoresRecorridos=disco.cantSectoresRecorridos(tiempoPedidos, TR);
      int sectoresRecorridos= disco.sectoresRecorridos(cantSectoresRecorridos);
      //disco.tiempoPedidos(tiempoDeBusqueda, cilindrosRecorridos);
      int tt= disco.tiempoTotal(cilindrosRecorridos, TR, sectoresRecorridos);
      r.settiempoTotalLabel(tt);
      r.settiempoCilindroLabel(tiempoPedidos);
      r.settiempoSectorLabel(sectoresRecorridos);
        
        
        
        
        //llenar tabla
        r.llenarTabla(disco.getPedidos(), disco.getCabezas(), disco.getCilindros(), disco.getSectores());
        }
       
      // else{JOptionPane.showMessageDialog(null, "Error. Ingrese los datos requeridos");}
    }//GEN-LAST:event_iniciarEjerciciosBtnActionPerformed

    private void menuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBtnActionPerformed
        // TODO add your handling code here:
        
        SimuladorDeDiscos menu= new SimuladorDeDiscos();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuBtnActionPerformed

    private void numeroDePlatosTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroDePlatosTxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_numeroDePlatosTxtActionPerformed
    public void setCorrecto(){
        int a, b,d,i,f,g,h;
        try{
        a= Integer.parseInt(numeroDePlatosTxt.getText());       
        b= Integer.parseInt(numeroDeCilindrosTxt.getText());
        d= Integer.parseInt(numeroDeSectoresxPistaTxt.getText());
        i= Integer.parseInt(tiempoDeBusquedaTxt.getText());
        f= Integer.parseInt(velocidadDeGiro.getText());
        g= Integer.parseInt(peticion1Txt.getText());
        h= Integer.parseInt(peticion2Txt.getText()); 
        }catch (Exception e){
        JOptionPane.showMessageDialog(null, "Datos deben de ser ingresados solo enteros positivos");
                correcto=false;
        }
       // esEntero(a);esEntero(b);esEntero(d);esEntero(i);esEntero(f);esEntero(g);esEntero(h);
       /*try{
                if(a>0)correcto=true;}
                catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Error. Ingrese los datos requeridos");
                    correcto=false;} 
        try{
                if(b>0)correcto=true;}
                catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Error. Ingrese los datos requeridos");
                    correcto=false;}
        try{
                if(d>0)correcto=true;}
                catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Error. Ingrese los datos requeridos");
                    correcto=false;}
        try{ if(j>0)correcto=true;}
                catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Error. Ingrese los datos requeridos");
                    correcto=false;}
        try{ if(f>0)correcto=true;}
                catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Error. Ingrese los datos requeridos");
                    correcto=false;}
        try{ if(g>0)correcto=true;}
                catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Error. Ingrese los datos requeridos");
                    correcto=false;}
        try{ if(h>0)correcto=true;}
                catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Error. Ingrese los datos requeridos");
                    correcto=false;}
              // correcto=true;*/

    }
     
        


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel busquedaLabel;
    private javax.swing.JLabel cilindrosLabel;
    private javax.swing.JButton iniciarEjerciciosBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton menuBtn;
    private javax.swing.JTextField numeroDeCilindrosTxt;
    private javax.swing.JTextField numeroDePlatosTxt;
    private javax.swing.JTextField numeroDeSectoresxPistaTxt;
    private javax.swing.JLabel peticion1Label;
    private javax.swing.JTextField peticion1Txt;
    private javax.swing.JLabel peticion2Label;
    private javax.swing.JTextField peticion2Txt;
    private javax.swing.JLabel platosLabel;
    private javax.swing.JLabel sectoresLabel;
    private javax.swing.JPanel simuladorPanel;
    private javax.swing.JTextField tiempoDeBusquedaTxt;
    private javax.swing.JTextField velocidadDeGiro;
    private javax.swing.JLabel velocidadLabel;
    // End of variables declaration//GEN-END:variables
}
