/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlanificacionDeDisco;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author irmal
 */
public class MostrarPlanificacion extends javax.swing.JFrame {
    DefaultTableModel modelTable = new DefaultTableModel();
    PlanificacionDeDisco planificacion;
    /**
     * Creates new form MostrarPlanificacion
     */
    public MostrarPlanificacion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public MostrarPlanificacion(int cabeza,String direccion,ArrayList solicitudes){
        initComponents();
        this.setLocationRelativeTo(null);
        this.planificacion = new PlanificacionDeDisco(cabeza, direccion, solicitudes);
        modelTable.addColumn("Pista Anterior");
        modelTable.addColumn("Pista Proxima");
        modelTable.addColumn("Numero Pistas Recorridas");
        planificacion.iniciarProcesoDePlanificacion();
        inicializarTablaDeResultados();
    }
    
    public void inicializarTablaDeResultados(){
        clearTable();
        String recorrido = jComboBoxRecorrido.getSelectedItem().toString();
        //JOptionPane.showMessageDialog(rootPane, recorrido);
        int anterior, proximo,pistasRecorridas;
        int acumulador = 0;
        double longitudMedia = 0;
        ArrayList<Integer> lista = getLista(recorrido);
        for(int i = 0;i < lista.size()-1;i++){
            anterior = lista.get(i);
            proximo = lista.get(i + 1);
            pistasRecorridas = Math.abs(anterior - proximo);
            modelTable.addRow(new Object[]{anterior,proximo,pistasRecorridas});
            acumulador += pistasRecorridas;
        }
        longitudMedia = (double)acumulador/JTablePlanificacion.getRowCount();//Se divide entre el numero de filas
        jTextFieldCabeza.setText(String.valueOf(this.planificacion.getCabeza()));
        jTextFieldTiempoTotal.setText(String.valueOf(acumulador));
        jTextFieldLongitudMedia.setText(String.valueOf(longitudMedia));
        jTextAreaSolicitudes.setText(this.planificacion.toString());
    }
    private ArrayList<Integer> getLista(String recorrido){
        if(recorrido.equals("FCFS"))//FCFS, SSTF, SCAN, C-SCAN, C-LOOK
            return planificacion.getSolicitudes();
        else if(recorrido.equals("SSTF"))
            return planificacion.recorrerSSTF();
        else if(recorrido.equals("SCAN"))
            return planificacion.recorrerSCAN();
        else if(recorrido.equals("C-SCAN"))
            return planificacion.recorrerC_SCAN();
        else 
            return planificacion.recorrerC_LOOK();
    }
    
    private void clearTable(){
        for(int i = modelTable.getRowCount()-1; i >= 0; i--){
            modelTable.removeRow(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTablePlanificacion = new javax.swing.JTable();
        menuBtn = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();
        jComboBoxRecorrido = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCabeza = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaSolicitudes = new javax.swing.JTextArea();
        jTextFieldTiempoTotal = new javax.swing.JTextField();
        jTextFieldLongitudMedia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador de Discos Duros");
        setResizable(false);

        jLabel1.setText("Tiempo total de espera:");

        jLabel2.setText("Longitud  media de espera:");

        JTablePlanificacion.setModel(modelTable);
        jScrollPane1.setViewportView(JTablePlanificacion);

        menuBtn.setText("Menu");
        menuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBtnActionPerformed(evt);
            }
        });

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        jComboBoxRecorrido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FCFS", "SSTF", "SCAN", "C-SCAN", "C-LOOK" }));
        jComboBoxRecorrido.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxRecorridoItemStateChanged(evt);
            }
        });

        jLabel3.setText("Recorrer como:");

        jLabel4.setText("Cabeza:");

        jTextFieldCabeza.setEditable(false);

        jLabel5.setText("Solicitudes:");

        jTextAreaSolicitudes.setEditable(false);
        jTextAreaSolicitudes.setColumns(20);
        jTextAreaSolicitudes.setRows(5);
        jScrollPane2.setViewportView(jTextAreaSolicitudes);

        jTextFieldTiempoTotal.setEditable(false);

        jTextFieldLongitudMedia.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxRecorrido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTiempoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jTextFieldLongitudMedia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(menuBtn)
                        .addGap(18, 18, 18)
                        .addComponent(volverBtn)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCabeza, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldCabeza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxRecorrido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTiempoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldLongitudMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(volverBtn)
                            .addComponent(menuBtn))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBtnActionPerformed
        // TODO add your handling code here:
        SimuladorDeDiscos menu= new SimuladorDeDiscos();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuBtnActionPerformed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        PlanificacionesPrincipal plan= new PlanificacionesPrincipal(); 
            plan.setVisible(true);
    }//GEN-LAST:event_volverBtnActionPerformed

    private void jComboBoxRecorridoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxRecorridoItemStateChanged
        // TODO add your handling code here:
        inicializarTablaDeResultados();
    }//GEN-LAST:event_jComboBoxRecorridoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarPlanificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarPlanificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarPlanificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarPlanificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarPlanificacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTablePlanificacion;
    private javax.swing.JComboBox<String> jComboBoxRecorrido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaSolicitudes;
    private javax.swing.JTextField jTextFieldCabeza;
    private javax.swing.JTextField jTextFieldLongitudMedia;
    private javax.swing.JTextField jTextFieldTiempoTotal;
    private javax.swing.JButton menuBtn;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
