/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PlanificacionDeDisco;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author irmal
 */
public class PlanificacionesPrincipal extends javax.swing.JFrame {
    boolean eleccion=false;
    private String direccion = "";
    ArrayList<Character> caracteresInvalidos = new ArrayList<>();
    DefaultListModel modelSolicitudes = new DefaultListModel<>();
    
    /**
     * Creates new form PlanificacionesPrincipal
     */
    public PlanificacionesPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.direccion = "Derecha";
        jRadioButtonDerecha.setSelected(true);
        //limpiarJlist();
        jListSolicitudes.setModel(modelSolicitudes);
        jFormattedTextFieldCabeza.setValue(0);
        activarCaracteresInvalidos();//aqui se agregaran los caracteres invalidos para los campos de textos
    }
    
    public DefaultListModel limpiarJlist(){
        DefaultListModel modelo = new DefaultListModel();
        jListSolicitudes.setModel(modelo);
        return modelo;
    }
    
    public DefaultListModel eliminarSolicitud(){
        modelSolicitudes.remove(jListSolicitudes.getSelectedIndex());
        return modelSolicitudes;
    }
    //Se agregaran los caracteres invalidos para validar los campos de textos
    public void activarCaracteresInvalidos(){
        this.caracteresInvalidos.add('+');
        this.caracteresInvalidos.add('=');
        this.caracteresInvalidos.add('-');
        this.caracteresInvalidos.add('/');
        this.caracteresInvalidos.add('*');
        this.caracteresInvalidos.add('|');
        this.caracteresInvalidos.add('.');
        this.caracteresInvalidos.add('_');
        this.caracteresInvalidos.add(' ');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDireccion = new javax.swing.ButtonGroup();
        iniciarPlanificaciones = new javax.swing.JButton();
        menuBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonDerecha = new javax.swing.JRadioButton();
        jRadioButtonIzquierda = new javax.swing.JRadioButton();
        jFormattedTextFieldCabeza = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSolicitudes = new javax.swing.JList<>();
        jButtonAgregarSolicitud = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador de Discos Duros");
        setResizable(false);

        iniciarPlanificaciones.setText("Iniciar");
        iniciarPlanificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarPlanificacionesActionPerformed(evt);
            }
        });

        menuBtn.setText("Menu");
        menuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingresar datos iniciales");

        jLabel3.setText("Cabeza");

        jLabel4.setText("Dirección");

        buttonGroupDireccion.add(jRadioButtonDerecha);
        jRadioButtonDerecha.setText("Derecha");
        jRadioButtonDerecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonDerechaMouseClicked(evt);
            }
        });

        buttonGroupDireccion.add(jRadioButtonIzquierda);
        jRadioButtonIzquierda.setText("Izquierda");
        jRadioButtonIzquierda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonIzquierdaMouseClicked(evt);
            }
        });

        jFormattedTextFieldCabeza.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextFieldCabeza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldCabezaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFormattedTextFieldCabeza, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonIzquierda)
                            .addComponent(jRadioButtonDerecha))))
                .addGap(83, 83, 83))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldCabeza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonDerecha)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonIzquierda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Ingresar solicitudes");

        jListSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListSolicitudesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListSolicitudes);

        jButtonAgregarSolicitud.setText("Agregar");
        jButtonAgregarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarSolicitudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAgregarSolicitud)
                        .addGap(21, 21, 21))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAgregarSolicitud)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(iniciarPlanificaciones)
                        .addGap(18, 18, 18)
                        .addComponent(menuBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuBtn)
                    .addComponent(iniciarPlanificaciones))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarPlanificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarPlanificacionesActionPerformed
        
        if(modelSolicitudes.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "No has agregado ninguna solicitud");
        }else if(modelSolicitudes.contains(Integer.parseInt(jFormattedTextFieldCabeza.getText()))){
            JOptionPane.showMessageDialog(rootPane, "La cabeza no puede ser parte de las solicitudes");
        }else{
            int cabeza = Integer.parseInt(jFormattedTextFieldCabeza.getText());
            ArrayList<Integer> solicitudes = new ArrayList<>();
            solicitudes.add(cabeza);//la cabeza es el primer elemento de la lista

            //JOptionPane.showMessageDialog(this, modelSolicitudes.size());
            for(int i = 0;i < modelSolicitudes.size();i++){
                //String j = String.valueOf(jListSolicitudes.getModel().getElementAt(i));
                solicitudes.add(Integer.parseInt(String.valueOf(jListSolicitudes.getModel().getElementAt(i))));
            }        

            MostrarPlanificacion plan= new MostrarPlanificacion(cabeza,this.direccion,solicitudes);
            plan.setVisible(true);
            this.setVisible(false);
        }
         
    }//GEN-LAST:event_iniciarPlanificacionesActionPerformed

    private void menuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBtnActionPerformed
        // TODO add your handling code here:
        SimuladorDeDiscos menu= new SimuladorDeDiscos();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuBtnActionPerformed

    private void jButtonAgregarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarSolicitudActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(this, this.direccion);
        //int cabeza = Integer.parseInt(jFormattedTextFieldCabeza.getText());
        //JOptionPane.showInternalMessageDialog(this, cabeza);
        int intSolicitud;String stringSolicitud = "";
        stringSolicitud = JOptionPane.showInputDialog(this, "Ingrese Solicitud", "Numero entereo").trim();
        try {
            intSolicitud = Integer.parseInt(stringSolicitud);
            if(!modelSolicitudes.contains(intSolicitud)&&intSolicitud != Integer.parseInt(jFormattedTextFieldCabeza.getText()))//No permite repetidos ni el valor de la cabeza
                modelSolicitudes.addElement(Math.abs(intSolicitud));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error: Ingrese una solicitud valida");
        }
    }//GEN-LAST:event_jButtonAgregarSolicitudActionPerformed

    private void jRadioButtonDerechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonDerechaMouseClicked
        // TODO add your handling code here:
        this.direccion = "Derecha";
        //JOptionPane.showMessageDialog(this,this.direccion);
    }//GEN-LAST:event_jRadioButtonDerechaMouseClicked

    private void jRadioButtonIzquierdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonIzquierdaMouseClicked
        // TODO add your handling code here:
        this.direccion = "Izquierda";
        //JOptionPane.showMessageDialog(this,this.direccion);
    }//GEN-LAST:event_jRadioButtonIzquierdaMouseClicked

    private void jListSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListSolicitudesMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2)
            eliminarSolicitud();
    }//GEN-LAST:event_jListSolicitudesMouseClicked

    private void jFormattedTextFieldCabezaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCabezaKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)||this.caracteresInvalidos.contains(validar)){
            getToolkit().beep();
            evt.consume();
            //JOptionPane.showMessageDialog(rootPane, "Ingresar solo numero");
        }
    }//GEN-LAST:event_jFormattedTextFieldCabezaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlanificacionesPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlanificacionesPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlanificacionesPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlanificacionesPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlanificacionesPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.ButtonGroup buttonGroupDireccion;
    private javax.swing.JButton iniciarPlanificaciones;
    private javax.swing.JButton jButtonAgregarSolicitud;
    private javax.swing.JFormattedTextField jFormattedTextFieldCabeza;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jListSolicitudes;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonDerecha;
    private javax.swing.JRadioButton jRadioButtonIzquierda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton menuBtn;
    // End of variables declaration//GEN-END:variables
}
